# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(unique=True, verbose_name='IP address')),
                ('status', models.CharField(choices=[('in_use', 'in use'), ('available', 'available'), ('not_available', 'not available')], max_length=15, verbose_name='Status')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Discription')),
            ],
        ),
    ]
